.TH berusky 6  "12/2/2010" "1.1" "berusky Man Page"
.SH NAME
.B berusky
- is a free logic game, published under GNU Public License and it's based on an ancient puzzle named Sokoban.
.SH SYNOPSIS
berusky [-e [level.lv3]] [-u level.lv3]

.SH OPTIONS
A summary of the options supported by berusky is included below.
.TP
.B \-e [level.lv3]
Run level editor
.TP
.B \-u level.lv3 
Run level "level.lv3"
.SH DESCRIPTION
.B berusky 
is a free logic game, published under GNU Public License and it's based on an ancient puzzle named Sokoban.

An old idea of moving boxes in a maze has been expanded with new logic items such as explosives, stones, special gates and so on. In addition, up to five bugs can cooperate and be controlled by the player. 
.SH VERSION
The last 
.B berusky
version is the 1.1
.SH AUTHORS
This package was written by Bart Martens
.br
<bartm@debian.org>
This little Man Page has been made by Braulio Valdivielso 
.br
<brlvldvlsmrtnz@gmail.com>
